name: QA and image building
on: [ push, pull_request ]

jobs:
  build:
    environment: Default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image
        run: |
          make image
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push image to docker hub
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          make push_image
